apiVersion: v1
kind: ConfigMap
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
data:
  config.inc.php: |
    <?php
    $i = 0;

    $i++;
    $cfg['Servers'][$i]['host'] = 'mysql';
    $cfg['Servers'][$i]['compress'] = 'false';
    $cfg['Servers'][$i]['AllowNoPassword'] = 'false';

    $cfg['blowfish_secret'] = 'i0ULtq/xlL:x;F7AjIYH=2I82cI[Vrly';
    $cfg['DefaultLang'] = 'en';
    $cfg['ServerDefault'] = 1;
    $cfg['UploadDir'] = '';
    $cfg['SaveDir'] = '';
    $cfg['PmaAbsoluteUri'] = '/phpmyadmin/';
    $cfg['Servers'][$i]['auth_type'] = 'cookie';
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  template:
    metadata:
      name: phpmyadmin
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin-image
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 3
          volumeMounts:
            - name: phpmyadmin-config
              subPath: config.inc.php
              mountPath: /var/www/localhost/htdocs/phpmyadmin/config.inc.php
              readOnly: true
      volumes:
        - name: phpmyadmin-config
          configMap:
            name: phpmyadmin
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  ports:
    - port: 5000
      name: phpmyadmin
      targetPort: 5000
